In [14]:
import pandas as pd
import os
# CWD = "/tmp"
# df_name = "initial_test_28042023-174438_main_structs.pkl"
CWD = "/home/psanz/teklahome/projects/p2-CuZn/initial_tests/final_tests_plot"
df_name = "result_df_test007_new.pkl"
df = pd.read_pickle(os.path.join(CWD, df_name))
# display(df["kpoints_Zn_pv_2005_0"])
# sub_df = df.loc[(df.base == True) & (df.phase.isin(['alpha','epsilon']))]
sub_df = df

display(sub_df)

# sub_df.to_pickle("/tmp/twoitem_df_test.pkl")

,material_id,structure,formula,symmetry,perturb,temperature,base,phase,magnetic_properties,energy_per_atom
0,mp-30,"[[0. 0. 0.] Cu, [0. 1.78459703 1.78459...",Cu4,"(Fm-3m, 225)",False,NaN,True,alpha,None,-4.238302
1,mp-972042,"[[2.66549432 3.05765727 3.18688289] Zn, [1.350...",Zn6 Cu2,"(P6_3/mmc, 194)",False,NaN,True,epsilon,None,-2.235243

In [15]:



import pandas as pd
import os
# CWD = "/tmp"
# df_name = "initial_test_28042023-174438_main_structs.pkl"
CWD = "/tmp"
df_name = "initial_test_05052023-120352_main_structs.pkl"
df = pd.read_pickle(os.path.join(CWD, df_name))
# display(df["kpoints_Zn_pv_2005_0"])
sub_df = df.loc[(df.material_id == 'mp-30_m1_super-3_2_3')]
sub_df2 = df.loc[(df.material_id == 'mp-30_alpha_super-3_1_2')]
# sub_df = df




from pymatgen.io.vasp import Poscar
sub_df.structure.values[0]

display(sub_df)
strct = Poscar(sub_df.structure.values[0], sort_structure=True)
strct.write_file('/tmp/POSCAR_m1')
# sub_df.to_pickle("/tmp/twoitem_df_test.pkl")

display(sub_df2)
strct2 = Poscar(sub_df2.structure.values[0], sort_structure=True)
strct2.write_file('/tmp/POSCAR_alpha')
# sub_df.to_pickle("/tmp/twoitem_df_test.pkl")

,material_id,structure,formula,symmetry,perturb,temperature,base,phase,magnetic_properties,energy_per_atom
127,mp-30_m1_super-3_2_3,"[[0. 0. 0.] Cu, [0. 0. 3.56919...",Zn46 Cu62,NaN,True,NaN,False,m1,None,NaN

,material_id,structure,formula,symmetry,perturb,temperature,base,phase,magnetic_properties,energy_per_atom
9,mp-30_alpha_super-3_1_2,"[[0. 0. 0.] Zn0+, [0. 0. 3.569...",Zn41 Cu67,NaN,True,NaN,False,alpha,None,NaN